/* eslint-disable */
/**
 * Generated `api` reference for Convex functions.
 *
 * This file is auto-generated by `npx convex dev` normally. It's been
 * hand-written for Phase 1 to allow offline development + testing.
 * Running `npx convex dev` will overwrite it with the real codegen output.
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as access_mutations from "../access/mutations.js";
import type * as access_queries from "../access/queries.js";
import type * as ingestion_embed from "../ingestion/embed.js";
import type * as ingestion_extract from "../ingestion/extract.js";
import type * as ingestion_ingest from "../ingestion/ingest.js";
import type * as ingestion_mutations from "../ingestion/mutations.js";
import type * as maintenance_backfill from "../maintenance/backfill.js";
import type * as maintenance_curator from "../maintenance/curator.js";
import type * as maintenance_dedup from "../maintenance/dedup.js";
import type * as maintenance_pruner from "../maintenance/pruner.js";
import type * as maintenance_tunnels from "../maintenance/tunnels.js";
import type * as migrations_runner from "../migrations/runner.js";
import type * as palace_mutations from "../palace/mutations.js";
import type * as palace_provision from "../palace/provision.js";
import type * as palace_queries from "../palace/queries.js";
import type * as serving_monitoring from "../serving/monitoring.js";
import type * as serving_assemble from "../serving/assemble.js";
import type * as serving_export from "../serving/export.js";
import type * as serving_l0l1 from "../serving/l0l1.js";
import type * as serving_rooms from "../serving/rooms.js";
import type * as serving_search from "../serving/search.js";
import type * as serving_tunnels from "../serving/tunnels.js";

declare const fullApi: ApiFromModules<{
  "access/mutations": typeof access_mutations;
  "access/queries": typeof access_queries;
  "ingestion/embed": typeof ingestion_embed;
  "ingestion/extract": typeof ingestion_extract;
  "ingestion/ingest": typeof ingestion_ingest;
  "ingestion/mutations": typeof ingestion_mutations;
  "maintenance/backfill": typeof maintenance_backfill;
  "maintenance/curator": typeof maintenance_curator;
  "maintenance/dedup": typeof maintenance_dedup;
  "maintenance/pruner": typeof maintenance_pruner;
  "maintenance/tunnels": typeof maintenance_tunnels;
  "migrations/runner": typeof migrations_runner;
  "palace/mutations": typeof palace_mutations;
  "palace/provision": typeof palace_provision;
  "palace/queries": typeof palace_queries;
  "serving/monitoring": typeof serving_monitoring;
  "serving/assemble": typeof serving_assemble;
  "serving/export": typeof serving_export;
  "serving/l0l1": typeof serving_l0l1;
  "serving/rooms": typeof serving_rooms;
  "serving/search": typeof serving_search;
  "serving/tunnels": typeof serving_tunnels;
}>;

export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
