/* eslint-disable */
/**
 * Generated `api` reference for Convex functions.
 *
 * This file is auto-generated by `npx convex dev` normally. It's been
 * hand-written for Phase 1 to allow offline development + testing.
 * Running `npx convex dev` will overwrite it with the real codegen output.
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as access_mutations from "../access/mutations.js";
import type * as access_queries from "../access/queries.js";
import type * as ingestion_mutations from "../ingestion/mutations.js";
import type * as migrations_runner from "../migrations/runner.js";
import type * as palace_mutations from "../palace/mutations.js";
import type * as palace_queries from "../palace/queries.js";

declare const fullApi: ApiFromModules<{
  "access/mutations": typeof access_mutations;
  "access/queries": typeof access_queries;
  "ingestion/mutations": typeof ingestion_mutations;
  "migrations/runner": typeof migrations_runner;
  "palace/mutations": typeof palace_mutations;
  "palace/queries": typeof palace_queries;
}>;

export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
